### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by cicerojones** [aberke/coloring-book#206]
A great project like this needs a great license! Have you thought much about this yet?

You might want to look over some of the github help articles in the [building community a strong community section](https://help.github.com/categories/building-a-strong-community/), like this one:

https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by aberke** [comment]
Thank you for those pointers!  After following those resources down a rabbit hole of research, I made PR https://github.com/aberke/coloring-book/pull/207 to add the GPL 3.

**Comment by cicerojones** [comment]
🎉 RMS would be proud! 🎉
